debug: false
server:
  servlet-path: /system

#management.security.enabled: false

cxf:
  path: /services
  #servlet.init: 
    #service-list-path: /info
  jaxrs:
    classes-scan: true
    classes-scan-packages: pe.com.jorgeberrios.crud,com.fasterxml.jackson.jaxrs.json

spring:
  profiles:
    active:
    - local
  datasource:
    url:
    username:
    password:
    driver-class-name:
      #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      show-sql: false
      open-in-view: false
#endpoints:
 # jmx:
   # enabled: true
   # unique-names: true  